

CREATE TABLE EQUIPOS (
  ID_EQUIPO     NUMBER(2),
  NOMBRE        VARCHAR2(50) CONSTRAINT EQUIPOS_NN1 NOT NULL,
  ESTADIO       VARCHAR2(50),
  AFORO         NUMBER(6),
  ANO_FUNDACION NUMBER(4),
  CIUDAD        VARCHAR2(50) CONSTRAINT EQUIPOS_NN2 NOT NULL,
  CONSTRAINT EQUIPOS_PK PRIMARY KEY (ID_EQUIPO),
  CONSTRAINT EQUIPOS_UK1 UNIQUE (NOMBRE),
  CONSTRAINT EQUIPOS_UK2 UNIQUE (ESTADIO)
);


CREATE TABLE PARTIDOS (
  ID_EQUIPO_CASA NUMBER(2),
  ID_EQUIPO_FUERA NUMBER(2),
  FECHA TIMESTAMP,
  GOLES_CASA NUMBER (2),
  GOLES_FUERA NUMBER(2),
  OBSERVACIONES VARCHAR2(1000),
  CONSTRAINT PARTIDOS_PK PRIMARY KEY (ID_EQUIPO_CASA,ID_EQUIPO_FUERA),
  CONSTRAINT PARTIDOS_FK1 FOREIGN KEY (ID_EQUIPO_FUERA) REFERENCES EQUIPOS (ID_EQUIPO) ON DELETE CASCADE ,
  CONSTRAINT PARTIDOS_FK2 FOREIGN KEY (ID_EQUIPO_CASA) REFERENCES EQUIPOS (ID_EQUIPO) ON DELETE CASCADE,
    CONSTRAINT PARTIDOS_CK CHECK (ID_EQUIPO_FUERA!=ID_EQUIPO_CASA)

);

CREATE TABLE JUGADORES (
  ID_JUGADOR NUMBER (3),
  NOMBRE VARCHAR2(50) CONSTRAINT JUGADORES_NN NOT NULL,
  FECHA_NAC DATE,
  ID_EQUIPO NUMBER (2),
  CONSTRAINT JUGADORES_PK PRIMARY KEY (ID_JUGADOR),
  CONSTRAINT JUGADORES_FK FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPOS (ID_EQUIPO) ON DELETE SET NULL

);

CREATE TABLE GOLES (
  ID_EQUIPO_CASA NUMBER (2),
  ID_EQUIPO_FUERA NUMBER (2),
  MINUTO INTERVAL DAY TO SECOND,
  DESCRIPCION VARCHAR2(2000),
  ID_JUGADOR NUMBER (3),
  CONSTRAINT GOLES_PK PRIMARY KEY  (ID_EQUIPO_CASA,ID_EQUIPO_FUERA,MINUTO),
  CONSTRAINT GOLES_FK1 FOREIGN KEY (ID_EQUIPO_FUERA,ID_EQUIPO_CASA) REFERENCES PARTIDOS (ID_EQUIPO_CASA,ID_EQUIPO_FUERA) ON DELETE CASCADE ,
  CONSTRAINT GOLES_FK2 FOREIGN KEY (ID_JUGADOR) REFERENCES JUGADORES (ID_JUGADOR) ON DELETE CASCADE ,
  CONSTRAINT GOLES_CK CHECK (ID_EQUIPO_FUERA=ID_EQUIPO_CASA)
);

ALTER TABLE EQUIPOS MODIFY AFORO CONSTRAINT  EQUIPOS_NN3 NOT NULL;
ALTER TABLE EQUIPOS MODIFY ESTADIO CONSTRAINT EQUIPOS_NN4 NOT NULL;


ALTER TABLE EQUIPOS MODIFY (ANO_FUNDACION DATE);


ALTER TABLE JUGADORES DROP CONSTRAINT JUGADORES_NN
