

CREATE TABLE PUESTOS (
  COD_PUESTO NUMBER (2),
  TITULO_PUESTO VARCHAR2(25) CONSTRAINT PUESTOS_NN NOT NULL,
  SALARIO_MIN NUMBER (11,2),
  SALARIO_MAX NUMBER (11,2),
  CONSTRAINT PUESTOS_PK PRIMARY KEY (COD_PUESTO),
  CONSTRAINT PUESTOS_UK UNIQUE (TITULO_PUESTO),
  CONSTRAINT PUESTOS_CK CHECK (SALARIO_MAX>SALARIO_MIN)
);

CREATE TABLE LOCALIZACIONES (
  COD_LOCALIZACION NUMBER (3),
  LOCALIDAD VARCHAR2(50) CONSTRAINT LOCALIZACIONES_NN NOT NULL,
  DIRECCION VARCHAR2(50),
  CP CHAR (5),
  PROVINCIA VARCHAR2(25),
  CONSTRAINT LOCALIZACIONES_PK PRIMARY KEY (COD_LOCALIZACION),
  CONSTRAINT LOCALIZACIONES_CK CHECK (CP<51000)
);

CREATE TABLE EMPLEADOS (
  COD_EMP NUMBER (4),
  NOMBRE VARCHAR2(50) CONSTRAINT EMPLEADOS_NN1 NOT NULL,
  APELLIDO1 VARCHAR2(50) CONSTRAINT EMPLEADOS_NN2 NOT NULL,
  APELLIDO2 VARCHAR2(50) CONSTRAINT EMPLEADOS_NN3 NOT NULL,
  TELEFONO CHAR (9),
  DIRECCION VARCHAR2(50),
  EMAIL VARCHAR2(50),
  COD_JEFE NUMBER (4),
  COD_DEP NUMBER (3),
  CONSTRAINT EMPLEADOS_PK PRIMARY KEY (COD_EMP),
  CONSTRAINT EMPLEADOS_UK UNIQUE (EMAIL),
  CONSTRAINT EMPLEADOS_FK1 FOREIGN KEY (COD_JEFE) REFERENCES EMPLEADOS (COD_EMP) ON DELETE CASCADE
);


CREATE TABLE HISTORIAL (
  COD_PUESTO NUMBER (2),
  COD_EMP NUMBER (4),
  FECHA_INICIO DATE CONSTRAINT HISTORIAL_NN NOT NULL,
  FECHA_FIN DATE,
  COD_DEP NUMBER (3),
  SALARIO NUMBER (11,2),
  CONSTRAINT HISTORIAL_PK PRIMARY KEY (COD_EMP,COD_PUESTO),
  CONSTRAINT HISTORIAL_FK1 FOREIGN KEY (COD_PUESTO) REFERENCES PUESTOS (COD_PUESTO) ON DELETE CASCADE ,
  CONSTRAINT HISTORIAL_CK1 CHECK (FECHA_FIN>FECHA_INICIO),
  CONSTRAINT HISTORIAL_CK2 CHECK (FECHA_INICIO>'1/01/1970')
);

CREATE TABLE DEPARTAMENTOS (
  COD_DEP NUMBER (2),
  NOMBRE_DEP VARCHAR2(25) CONSTRAINT DEPARTAMENTOS_NN NOT NULL,
  COD_RESP NUMBER (4),
  COD_LOC NUMBER (3),
  CONSTRAINT DEPARTAMENTOS_PK PRIMARY KEY (COD_DEP),
  CONSTRAINT DEPARTAMENTOS_FK2 FOREIGN KEY (COD_LOC) REFERENCES LOCALIZACIONES (COD_LOCALIZACION) ON DELETE CASCADE );

ALTER TABLE EMPLEADOS ADD CONSTRAINT EMPLEADOS_FK2 FOREIGN KEY (COD_DEP) REFERENCES DEPARTAMENTOS